name: download_assets
description: Download and uncompress assets
version: 2.0.0
homepage: https://github.com/edjostenes/download_assets

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.4
  path_provider: ^2.0.7
  archive: ^3.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: