name: download_assets
description: Download and uncompress assets
version: 3.0.4
homepage: https://github.com/edjostenes/download_assets

environment:
  sdk: '>=2.23.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.1.2
  path: ^1.8.3
  archive: ^3.3.7
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter: