name: download_assets
description: Retrieve assets and add them to the application's repository for use.
version: 3.1.1
homepage: https://github.com/edjostenes/download_assets

environment:
  sdk: '>=2.23.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.2.1+1
  path: ^1.8.3
  archive: ^3.3.7
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter: