name: download_assets
description: Download and uncompress assets in the user device basically, read the documentation for more information about this package.
version: 3.0.5
homepage: https://github.com/edjostenes/download_assets

environment:
  sdk: '>=2.23.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.1.2
  archive: ^3.3.7
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter: